name = "api"
main = "src/index.ts"
compatibility_date = "2026-07-10"
compatibility_flags = ["nodejs_compat"]
account_id = "85cd0e23088e12759d05b347f0f68536"

[vars]
PAGES_ORIGIN = "https://rumaq.pages.dev"
EMAIL_AUTH_ENABLED = "true"
RUN_SECRETS_CHECK = "true"

[[d1_databases]]
binding = "DB"
database_name = "rumaq"
database_id = "0591e773-0f1b-48c9-b931-8280a00b9068"

[[r2_buckets]]
binding = "RECEIPTS"
bucket_name = "rumaq-receipts"

[cache]
enabled = true

[exports.default]
type = "worker"

[exports.default.cache]
enabled = false

[exports.CachedApi]
type = "worker"

[exports.CachedApi.cache]
enabled = true
