import { writeFileSync } from 'node:fs'
import { generateSpecs } from 'hono-openapi'
import { apiApp } from '../backend/src/apps/api.js'
import { authApp } from '../backend/src/apps/auth.js'

const DOCS_OPTIONS = {
  documentation: {
    info: { title: 'RumaQ API', version: '0.1.0' },
    components: {
      securitySchemes: {
        cookieAuth: { type: 'apiKey' as const, in: 'cookie' as const, name: 'rumaq_session' },
      },
    },
  },
}

const AUTH_PATH_REMAP: Record<string, string> = {
  '/login': '/api/auth/login',
  '/callback': '/api/auth/callback',
  '/logout': '/api/auth/logout',
  '/email-login': '/api/auth/email-login',
}

const EXCLUDE_PATHS = new Set(['/api/openapi.json', '/openapi.json'])

type PathEntry = {
  method: string
  path: string
  auth: string
  query: string
  body: string
  description: string
}

function getQueryParams(operation: any): string {
  if (!operation.parameters || operation.parameters.length === 0) return '—'
  return operation.parameters
    .map((p: any) => {
      const suffix = p.required ? '' : '?'
      return `\`${p.name}${suffix}\``
    })
    .join(', ')
}

function getBodyInfo(operation: any): string {
  if (!operation.requestBody) return '—'
  const content = operation.requestBody.content
  if (!content || !content['application/json']) return '`{ ... }`'
  const schema = content['application/json'].schema
  if (!schema || !schema.properties) return '`{ ... }`'
  const props = Object.keys(schema.properties)
  if (props.length === 0) return '`{ }`'
  return `\`{ ${props.join(', ')} }\``
}

function extractEntries(paths: Record<string, any>): PathEntry[] {
  const entries: PathEntry[] = []
  for (let [path, methods] of Object.entries(paths)) {
    if (EXCLUDE_PATHS.has(path)) continue
    path = AUTH_PATH_REMAP[path] || path
    for (const [method, op] of Object.entries(methods as any)) {
      const isAuth = !!(op.security && op.security.length > 0)
      entries.push({
        method: method.toUpperCase(),
        path,
        auth: isAuth ? 'Yes' : '—',
        query: getQueryParams(op),
        body: getBodyInfo(op),
        description: op.description || '',
      })
    }
  }
  entries.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method))
  return entries
}

function buildMarkdown(paths: Record<string, any>): string {
  const entries = extractEntries(paths)

  let md = `# RumaQ — REST API Contract

Base URL: \`https://api.rumaq.workers.dev/api\`

All paths are relative to this base. The Worker mounts routes under \`/api/*\`.
Protected endpoints require the \`rumaq_session\` cookie. Responses are JSON.
Errors use \`{ "error": "..." }\`.

> This file is generated by \`./scripts/docs-api.sh\`. Do not edit manually.

## Caching

- **Public GET endpoints** (\`/health\`, \`/auth/email-status\`): \`Cache-Control: public, max-age=60\`.
- **Authenticated GET endpoints** (\`/me\`, \`/stock\`): \`Cache-Control: private, no-cache\` — never cached at the edge.
- **Error responses**: \`Cache-Control: private, no-cache\`.

## Implemented endpoints

| Method | Path                     | Auth | Query               | Body                  | Description                                                                                |
| ------ | ------------------------ | ---- | ------------------- | --------------------- | ------------------------------------------------------------------------------------------ |
`

  for (const e of entries) {
    const method = e.method.padEnd(6)
    const path = e.path.padEnd(24)
    const auth = e.auth.padEnd(4)
    const query = e.query.padEnd(19)
    const body = e.body.padEnd(21)
    md += `| ${method} | ${path} | ${auth} | ${query} | ${body} | ${e.description} |\n`
  }

  md += `\n## Planned endpoints\n\nThe following contracts are planned but not yet implemented:\n\n### Households\n\n- \`GET /households\` — list households for the current user.\n- \`POST /households\` — create a household.\n- \`PATCH /households/:id\` — update household name or active status.\n\n### Purchases\n\n- \`GET /purchases?store=&from=&to=\` — purchase history grouped by month.\n- \`POST /purchases\` — record a confirmed purchase and update stock.\n- \`POST /purchases/scan\` — upload a receipt image, run AI OCR, return parsed line items.\n\n### Plans\n\n- \`GET /plans?status=active\` — list shopping plans.\n- \`POST /plans/generate\` — ask AI to generate a shopping plan.\n- \`POST /plans\` — save a generated plan as active.\n- \`PATCH /plans/:id/items/:itemId\` — mark a plan item as bought or skipped.\n\n### Locations & Stores\n\n- \`GET /locations\`, \`POST /locations\`, \`DELETE /locations/:id\`\n- \`GET /stores\`, \`POST /stores\`, \`DELETE /stores/:id\`\n\n### Settings\n\n- \`GET /settings\` — get current user settings.\n- \`PATCH /settings\` — update settings.\n\n### AI Assistant\n\n- \`POST /ai/chat\` — send a message to the AI assistant.\n- \`GET /ai/usage\` — today's AI usage meter.\n`

  return md
}

async function main() {
  const [apiSpec, authSpec] = await Promise.all([
    generateSpecs(apiApp, DOCS_OPTIONS),
    generateSpecs(authApp, DOCS_OPTIONS),
  ])

  const allPaths: Record<string, any> = { ...apiSpec.paths }
  for (const [authPath, methods] of Object.entries(authSpec.paths)) {
    allPaths[authPath] = methods
  }

  // Manually add /api/auth/logout since 'ALL' methods don't appear in generateSpecs output
  allPaths['/logout'] = {
    ...allPaths['/logout'],
    get: {
      operationId: 'getLogout',
      description: 'Clears the session cookie. POST returns { ok: true }; GET redirects to {origin}.',
      responses: {
        '200': { description: 'OK' },
        '302': { description: 'Redirect (GET)' },
      },
    },
  }

  const markdown = buildMarkdown(allPaths)
  writeFileSync('docs/API.md', markdown, 'utf-8')
  console.log('✓ Generated docs/API.md')
}

main().catch((err) => {
  console.error('Failed to generate API docs:', err)
  process.exit(1)
})
